updated translation system
esx-framework/esx_animations pull request #4
Opened 2023-04-01 17:28 UTC by pecedevelopment

using TranslateCap function

2023-04-02 09:45 UTC, Thekuca requested changes
client/main.lua: check discord

2023-06-15 23:55 UTC, Gellipapa commented on .editorconfig
> +root = true
Not add editorconfig please remove this file, and use .gitignore.

2023-06-15 23:56 UTC, Gellipapa commented on client/main.lua
> +					title  = Config.Animations[i].items[j].data.index and Config.Animations[i].items[j].label..Config.Animations[i].items[j].data.index or Config.Animations[i].items[j].label,
Add variable this is unreadable please.

2023-06-15 23:56 UTC, Gellipapa commented on fxmanifest.lua
>  legacyversion '1.9.1'
Change legacy version please latest.

2023-06-15 23:57 UTC, Gellipapa commented on fxmanifest.lua
> +	'client/main.lua',
remove "," please.

2023-06-15 23:58 UTC, Gellipapa requested changes
don't remove localization configs revert this changes.

2023-06-20 09:47 UTC, pecedevelopment commented on .editorconfig
> +root = true
done

2023-06-23 18:24 UTC, Gellipapa commented
@pecedevelopment Open new pull request i closed this because is so big conflicts.

2023-06-23 18:24 UTC, closed without merging